#pragma once

# define USER_IDENTIFIER(nickname, username) (":" + nickname + "!" + username + "@localhost")

# define RPL_WELCOME(user_id, nickname) (user_id + " 001 " + nickname + " :Welcome to the Internet Relay Network " + user_id + "\r\n")
# define RPL_YOURHOST(user_id, nickname, servername, version) (user_id + " 002 " + nickname + " :Your host is " + servername + " (localhost), running version " + version + "\r\n")
# define RPL_CREATED(user_id, nickname, date) (user_id + " 003 " + nickname + " :This server was created " + date + "\r\n")
# define RPL_TOPIC(user_id, nickname, channel, topic) (user_id + " 332 " + nickname + " " + channel + " :" + topic + "\r\n")
# define RPL_NOTOPIC(user_id, nickname, channel) (user_id + " 331 " + nickname + " " + channel + " :No topic is set." + "\r\n")
# define RPL_NAMREPLY(user_id, nickname, channel, userList) (user_id + " 353 " + nickname + " = " + channel + " :" + userList + "\r\n")
# define RPL_ENDOFNAMES(user_id, nickname, channel) (user_id + " 366 " + nickname + " " + channel + " :End of /NAMES list" + "\r\n")
# define RPL_INVITING(user_id, nickname, channel, requested) (user_id + " 341 " + nickname + " " + channel + " " + requested + "\r\n")
# define RPL_CHANNELMODEIS(user_id, nickname, channel, mode) (user_id + " 324 " + nickname + " " + channel + " " + mode + "\r\n")
# define RPL_UMODEIS(user_id, nickname, mode) (user_id + " 221 " + nickname + " " + mode + "\r\n")
# define RPL_WHOREPLY(user_id, channel, username, hostname, servername, nickname, status, hopcount) (user_id + " 352 " + channel + " " + username + " " + hostname + " " + servername + " " + nickname + " " + status + " " + hopcount + " :" + nickname + "\r\n")

# define ERR_UKNOWNMODE(user_id, nickname, modeChar) (user_id + " 472 " + nickname + " " + modeChar + " :is unknown mode char to me" + "\r\n")
# define ERR_UMODEUNKNOWNFLAG(user_id, nickname) (user_id + " 501 " + nickname + " :Unknown MODE flag" + "\r\n")
# define ERR_USERONCHANNEL(user_id, nickname, channel, requested) (user_id + " 443 " + nickname + " " + channel + " " + requested + " :is already on channel" + "\r\n")
# define ERR_NOTEXTTOSEND(user_id, nickname) (user_id + " 412 " + nickname + " :No text to send" + "\r\n")
# define ERR_NOTREGISTERED(user_id, nickname) (user_id + " 451 " + nickname + " :You have not registered" + "\r\n")
# define ERR_NOSUCHNICK(user_id, nickname, requested) (user_id + " 401 " + nickname + " " + requested + " :No such nick/channel" + "\r\n")
# define ERR_NOSUCHCHANNEL(user_id, nickname, channel) (user_id + " 403 " + nickname + " " + channel + " :No such channel" + "\r\n")
# define ERR_USERNOTINCHANNEL(user_id, nickname, channel, requested) (user_id + " 441 " + nickname + " " + channel + " " + requested + " :They aren't on that channel" + "\r\n")
# define ERR_NORECIPIENT(user_id, nickname, command) (user_id + " 411 " + nickname + " " + command + " :No recipient given" + "\r\n")
# define ERR_NOTONCHANNEL(user_id, nickname, channel) (user_id + " 442 " + nickname + " " + channel + " :You're not on that channel" + "\r\n")
# define ERR_NEEDMOREPARAMS(user_id, nickname, command) (user_id + " 461 " + nickname + " " + command + " :Not enough parameters" + "\r\n")
# define ERR_ALREADYREGISTRED(user_id, nickname) (user_id + " 462 " + nickname + " :You may not reregister" + "\r\n")
# define ERR_PASSWDMISMATCH(user_id, nickname) (user_id + " 464 " + nickname + " :Password incorrect" + "\r\n")
# define ERR_NONICKNAMEGIVEN(user_id, nickname) (user_id + " 431 " + nickname + " :No nickname given" + "\r\n")
# define ERR_ERRONEUSNICKNAME(user_id, nickname, requested) (user_id + " 432 " + nickname + " " + requested + " :Erroneus nickname" + "\r\n")
# define ERR_NICKNAMEINUSE(user_id, nickname, requested) (user_id + " 433 " + nickname + " " + requested + " :Nickname is already in use" + "\r\n")
# define ERR_CHANNELISFULL(user_id, nickname, channel) (user_id + " 471 " + nickname + " " + channel + " :Cannot join channel (+l)" + "\r\n")
# define ERR_UNKNOWNMODE(user_id, nickname, modeChar) (user_id + " 472 " + nickname + " " + modeChar + " :is unknown mode char to me" + "\r\n")
# define ERR_INVITEONLYCHAN(user_id, nickname, channel) (user_id + " 473 " + nickname + " " + channel + " :Cannot join channel (+i)" + "\r\n")
# define ERR_BADCHANMASK(user_id, nickname, channel) (user_id + " 476 " + nickname + " " + channel + " :Incorrect format" + "\r\n")
# define ERR_BADCHANNELKEY(user_id, nickname, channel) (user_id + " 475 " + nickname + " " + channel + " :Cannot join channel (+k)" + "\r\n")
# define ERR_CHANOPRIVSNEEDED(user_id, nickname, channel) (user_id + " 482 " + nickname + " " + channel + " :You're not channel operator" + "\r\n")
#define ERR_UNKNOWNCOMMAND(source, nick, command) (source + " 421 " + nick + " " + command + " :Unknown command\r\n")